version: 0.0
os: linux
files:
  - source: / # Esto significa todo el contenido del artefacto de CodeBuild
    destination: /var/www/html/logandoportfolio/ # Tu carpeta de destino en EC2
permissions:
  - object: /var/www/html/logandoportfolio/
    pattern: "**"
    owner: root # <--- AJUSTA ESTO SI TU USUARIO ES DIFERENTE
    group: root # <--- AJUSTA ESTO SI TU GRUPO ES DIFERENTE
    mode: 644
    type:
      - file
  - object: /var/www/html/logandoportfolio/
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/restart_web_server.sh
      timeout: 300
      runas: root
