version: 0.0
os: linux
files:
  - source: / 
    destination: /var/www/html/logandoportfolio/ # Tu carpeta de destino en EC2
permissions:
  - object: /var/www/html/logandoportfolio/
    pattern: "**"
    owner: root 
    group: root 
    mode: 644
    type:
      - file
  - object: /var/www/html/logandoportfolio/
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
   - location: scripts/clean_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/restart_web_server.sh
      timeout: 60
      runas: root
