version: 0.2
phases:
  install:
    commands:
      - echo "Instalando Hugo..."
      - apt-get update -y
      - apt-get install -y wget # O curl si lo prefieres
      # Descarga la última versión de Hugo (ajusta la URL si necesitas una versión específica)
      # Usamos un bloque literal (|) para evitar problemas con los caracteres de escape de grep
      - |
        HUGO_VERSION=$(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -oP '"tag_name": "\Kv[^"]+')
      - HUGO_TARBALL="hugo_extended_${HUGO_VERSION#v}_linux-amd64.tar.gz"
      - wget https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/${HUGO_TARBALL}
      - tar -xzf ${HUGO_TARBALL} hugo
      - mv hugo /usr/local/bin/hugo
      - hugo version
  build:
    commands:
      - echo "Construyendo sitio Hugo..."
      - hugo # Ejecuta el comando Hugo para construir tu sitio
artifacts:
  files:
    - '**/*' # Incluye todos los archivos generados
  base-directory: public # Indica que la raíz del artefacto es la carpeta 'public' de Hugo
