version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      # Actualizar paquetes e instalar wget y sed
      - apt-get update -y
      - apt-get install -y wget sed

      # Descargar Hugo (asegúrate de que la URL y el sed sigan siendo correctos)
      - |
        LATEST_TAG=$(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -n 's/.*"tag_name": "\([^"]*\)".*/\1/p')
        wget "https://github.com/gohugoio/hugo/releases/download/${LATEST_TAG}/hugo_extended_${LATEST_TAG:1}_Linux-64bit.deb" -O /tmp/hugo.deb
        sudo dpkg -i /tmp/hugo.deb
      # Instalar npm y dependencias si tu proyecto las necesita
      - npm install
  build:
    commands:
      # Compilar el sitio Hugo
      - hugo
artifacts:
  files:
    - '**/*' # Incluye todos los archivos generados por Hugo dentro de 'public'
    - 'appspec.yml' # <--- ¡AÑADIDO! Incluye el appspec.yml desde la raíz del repositorio
    - 'scripts/**/*' # <--- ¡AÑADIDO! Incluye todos los scripts de la carpeta 'scripts'
  base-directory: public # La carpeta 'public' será la raíz del contenido web en el artefacto
