version: 0.2
phases:
  install: 
   commands:
      - echo "Instalando Hugo..."
      - apt-get update -y
      - apt-get install -y wget
      - |
        HUGO_VERSION=$(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -oP '"tag_name": "\Kv[^"]+'

        HUGO_TARBALL="hugo_extended_${HUGO_VERSION#v}_linux-amd64.tar.gz"
      - wget https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/${HUGO_TARBALL}
      - tar -xzf ${HUGO_TARBALL} hugo
      - mv hugo /usr/local/bin/hugo
      - hugo version
  build:
    commands:
      - echo "Construyendo sitio Hugo..."
      - hugo
artifacts:
  files:
    - '**/*' # Incluye todos los archivos generados por Hugo dentro de 'public'
    - 'appspec.yml' # <--- ¡AÑADIDO! Incluye el appspec.yml desde la raíz del repositorio
    - 'scripts/**/*' # <--- ¡AÑADIDO! Incluye todos los scripts de la carpeta 'scripts'
  base-directory: public # La carpeta 'public' será la raíz del contenido web en el artefacto
